# Generated by Django 5.2.1 on 2025-06-06 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='hourly_rate',
        ),
    ]
