# Generated by Django 5.2.1 on 2025-06-07 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_employee_hourly_rate_product_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='selling_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
    ]
