# Generated by Django 5.2.1 on 2025-06-08 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_product_selling_price_remove_product_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='customer',
        ),
    ]
