# Generated by Django 5.2.1 on 2025-06-08 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_salesorder_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity_on_hand',
            new_name='quantity',
        ),
    ]
