# Generated by Django 5.2.1 on 2025-07-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('HR', 'HR'), ('FINANCE', 'Finance'), ('SALES', 'Sales'), ('ADMIN', 'Administrator')], max_length=20),
        ),
    ]
