# Generated by Django 5.2.1 on 2025-06-15 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_quantity_on_hand_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='hours_worked',
        ),
        migrations.AddField(
            model_name='payroll',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='net_pay',
            field=models.DecimalField(decimal_places=2, default=datetime.datetime(2025, 6, 15, 20, 45, 38, 316062, tzinfo=datetime.timezone.utc), max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payroll',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Processing', 'Processing'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
