# Generated by Django 5.2.1 on 2025-06-21 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_payroll_hours_worked_payroll_bonus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='hourly_rate',
        ),
    ]
